README.rst, paragon/_overrides.scss, paragon/_variables.scss
See the theme in this PR applied to the Paragon docsite here: https://paragon-edx-next.netlify.app/
Notable changes:
- The `$base-font-size` is now 18px instead of 16px.
- There is a "brand" theme-color that is undocumented (since this PR doesn't affect the Paragon doc site). You can preview the brand button by using the interactive code editor and adding a Button with the variants: `variant="brand"` or `variant="outline-brand"`
=> feat: update the paragon theme with new branding

paragon/_overrides.scss, paragon/_variables.scss
I came across issues while integrating `brand-edx.org` with edx-platfrom. 
The first issue was wrong number of arguments for the `theme-color` function. 
I resolved the issue by passing a single argument to the function call. 
Once that issue is resolved the second issue was `$form-validation-states is not defined`.
`$form-validation-states` variable is used at https://github.com/edx/brand-edx.org/blob/master/paragon/_overrides.scss#L68 but it was not initialized anywhere in `brand-edx.org`.  I observed that the variable actually exists and was commented-out in `_variables.scss` See here. https://github.com/edx/brand-edx.org/blob/master/paragon/_variables.scss#L737-L750
This might not be a perfect solution but it worked and I am happy to know if there are other (better) ways to address …
=> fix: Fixing installation issues

paragon/_variables.scss
Update to match the color system below. Notable adds light and dark color ramps to simplify use of primary and secondary theme colors.
See the paragon docs with this theme here: https://paragon-edx-next.netlify.app/foundations/colors
=> fix: colors update

paragon/_overrides.scss, paragon/_variables.scss
=> fix: remove underlines for links outside paragraphs

paragon/theme.scss, paragon/utilities-only.scss
These are left over from copying the original edx theme out of Paragon. The relative paths inside them wouldn't point to anything and won't compile so it's safe to assume they are unused.
=> fix: remove unused scss files

paragon/_overrides.scss
We have no control over the distance of the underline to the text, but we avoid problematic issues with creating underlines beneath image links:
Solves:
=> fix: use text decoration for link styles

paragon/_variables.scss
These variables were added to this theme in error. Consuming applications should only use variable names that also exist in the Paragon core (`$primary-300`, `$light`, etc).
After we confirm that no consuming applications use these edx-specific variables, we'll delete them.
=> fix: deprecate edx specific color variables

paragon/_overrides.scss
Theming for the new Avatar Button component https://github.com/edx/paragon/pull/593
From
To
=> fix: darken text of default avatar button style

paragon/_variables.scss
Darken info blue so that it maintains 4.5:1 contrast on all 100 level utility colors and light 500 - 100.
=> fix: darken blue for color contrast

paragon/_variables.scss
All font sizes are the same on mobile, except h1 which is slightly smaller.
=> fix: update mobile heading font sizes

paragon/_overrides.scss, paragon/_variables.scss
[PAR-260](https://openedx.atlassian.net/browse/PAR-260)
Minor updates to line-heights on the type ramp. Also adds the new `$x-small-font-size` as introduced in https://github.com/edx/paragon/pull/604
=> fix: update typography to match design

paragon/_overrides.scss, paragon/_variables.scss
@abutterworth 
Ticket on Jira: https://openedx.atlassian.net/browse/PAR-287
Update badge component according to the new design: https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-2021?node-id=6703%3A52
=> [BD-35] PAR-287 feat: change styles according to new badge component design

paragon/_variables.scss
@abutterworth 
Change default color on tooltip component according to new design
=> [BD-35] PAR-282 fix: change default color to primary in tooltip variables

paragon/_overrides.scss, paragon/_variables.scss
Minor updates to fix bumps in the existing color ramp and prevent grays from being too light:
now:
Also includes a change to select indicators (since the appropriate style is being defined in Paragon itself) and the default input background.
=> fix: update to primary and gray color ramps and container max width

paragon/_overrides.scss
=> fix: update button outline color

paragon/_overrides.scss
Update the division operator so we can use these files with sass >= 1.33.0 https://sass-lang.com/documentation/breaking-changes/slash-div
=> fix: update use of division operator to fix for sass breaking change

.github/workflows/release.yml
Upgrade to node 16 to fix use of `semantic-release`
=> fix: upgrade to node 16

paragon/_overrides.scss
The previous PR #39 caused some sandbox builds to break, for example [this one](https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/45920/console) on frontend-app-authn. In that PR we changed some implicit division calculations to be wrapped with `calc`. However we only wrapped the division operator and not the multiplication. This worked fine on later versions of sass starting at `1.40.1` (see [changelog](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1401)), but `frontend-app-authn` used `1.26.11` which did not handle multiplication of a `calc` function with another number. The error was: `SassError: Undefined operation "calc(44 / 16) * 1rem".`
This PR moves the multiplications inside the calc function so that dart-sass can handle them appropriately, for …
=> fix: include multiplication in calc function

paragon/_variables.scss
Explicitly specify pixel values for `Button` border-radius variable since this values is used in `calc` method and leaving it as just `0` led to incorrect border-radius being applied in Paragon (`calc` doesn't know how to work with zeros), see [PAR-764](https://openedx.atlassian.net/browse/PAR-764) for reference
=> [BD-46] fix: use pixel values for button border-radius variable

paragon/_variables.scss, paragon/css/core/variables.css, tokens/src/core/global/spacing.json
Issue: https://github.com/openedx/paragon/issues/2356
- Ensure $grid-gutter-width has a design token and associated CSS variable.
- Use above CSS variable in _overrides.scss and in core.scss with @edx/brand-edx.org
=> feat: added grid-gutter-width token

paragon/css/core/index.css
When `core.css` or `core.min.css` loads in the browser, the stylesheet's loading gets render-blocked by a CSS `@import` for the `Inter` Google Font:
```css
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Roboto+Mono&display=swap');
```
This `@import` means that users must first download the `core.min.css`, parse it, and then perform the dynamic `@import` for the `Inter` font:
This PR releases a version of `alpha` that does not include the dynamic `@import` to rely instead of a `<link rel="preload" as="font">` instead to see any performance differences in render-blocking content.
=> chore: experiment with not including font @import in CSS, but rather via `<link>` in HTML

paragon/css/core/index.css, paragon/css/core/variables.css, tokens/src/core/components/Popover.json
Missing arrow in Popover component (only Brand-Edx.org theme)
**Issue:** https://github.com/openedx/paragon/issues/2799
=> [BD-46] fix: fixed Popover arrow
